export const mockData = [
  {
    code: 'T204998',
    title: '자료구조',
    cells: [
      { name: '타과1', value: 0 },
      { name: '타과2', value: 0 },
      { name: '타과3', value: 0 },
      { name: '타과4', value: 0 },
      { name: '편입', value: 0 },
      { name: '차과', value: 25 },
    ],
    info: {
      type: 'A',
      lectureType: '전선',
      credits: '3학년',
      timePeriod: '주간',
      professor: '권민서',
    },
    time: '창의관501 수1~3M',
  },
  {
    code: 'T204999',
    title: '알고리즘',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학년',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  {
    code: 'T204990',
    title: '객체 지향 언어',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학년',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  {
    code: 'T204991',
    title: '데이터 베이스',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학년',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  {
    code  : 'T204992',
    title: '데이터 통신',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학년',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  {
    code: 'T204993',
    title: '응용 수학',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학년',
      timePeriod: '야간',
      professor: '권민서',
    },
    time: '공학관102 목3~5M',
  },
  {
    code: 'T204994',
    title: '웹 프레임 워크',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학년',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  
  // 추가
];
