export const mockData = [
  {
    title: '[T204998] 자료구조',
    cells: [
      { name: '타과1', value: 0 },
      { name: '타과2', value: 0 },
      { name: '타과3', value: 0 },
      { name: '타과4', value: 0 },
      { name: '편입', value: 0 },
      { name: '차과', value: 25 },
    ],
    info: {
      type: 'A',
      lectureType: '전선',
      credits: '3학점',
      timePeriod: '주간',
      professor: '권민서',
    },
    time: '창의관501 수1~3M',
  },
  {
    title: '[T204999] 알고리즘',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학점',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  {
    title: '[T204990] 객체 지향 언어',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학점',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  {
    title: '[T205599] 데이터 베이스',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학점',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  {
    title: '[T204499] 데이터 통신',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학점',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  {
    title: '[T201111] 응용 수학',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학점',
      timePeriod: '야간',
      professor: '권민서',
    },
    time: '공학관102 목3~5M',
  },
  {
    title: '[T208829] 웹 프레임 워크',
    cells: [
      { name: '타과1', value: 10 },
      { name: '타과2', value: 5 },
      { name: '타과3', value: 3 },
      { name: '타과4', value: 4 },
      { name: '편입', value: 2 },
      { name: '차과', value: 15 },
    ],
    info: {
      type: 'B',
      lectureType: '전필',
      credits: '4학점',
      timePeriod: '야간',
      professor: '김수한',
    },
    time: '공학관102 목3~5M',
  },
  
  // 추가
];
